### ISSUE TITLE
Doubled "Add-on Bar" (Classic Theme Restorer conflict)

### ISSUE THREAD

**Issue by ache** [SparkyBluefang/S4E#25]
Hi. Your addon and "Classic Theme Restorer" addon both make toolbars under the same name "Add-on Bar" which is doubled as result, not merged into single one. Please reach some agreement with "Classic Theme Restorer" author or make this toolbar optional (I can't find a way to turn it off).

**Comment by SparkyBluefang** [comment]
The S4E provided status bar is called "Status Bar". It can be toggled on and off like any other toolbar.

Both the S4E and CTR toolbars are customizable, so place the desired items on one and hide the other.
