### ISSUE TITLE
Download icon disappears in FF35

### ISSUE THREAD

**Issue by KilliK69** [SparkyBluefang/S4E#28]
There is a bug in FF35.

When a download completes, the download icon of the addon disappears. 
If you click the empty area where it used to be, the icon will reappear, otherwise it wont.
If you download again, it will disappear again.

I have tested it in a fresh profile and the problem remains.

This needs a fix.

**Comment by SparkyBluefang** [comment]
Fixed by 5802708098206e634fe5649f60e91e41f0f336b7
