### ISSUE TITLE
Shows floating message in fullscreen

### ISSUE THREAD

**Issue by CennoxX** [SparkyBluefang/S4E#30]
At Google Drive the detection, that a html5 player is running in fullscreen doesn't work and floating messages (like here in the left) are displayed.
![example](https://cloud.githubusercontent.com/assets/6975881/8980594/3440537c-36b2-11e5-8837-53eadd8648c5.jpg)

**Comment by SparkyBluefang** [comment]
This should be fixed by 3c9b2f980a4b03826ca44ae69ae62b6032a26290 and ae0100cbaf9ae79f670ee90e1d61c0c380b5590b

Give the latest beta version a try.

https://addons.mozilla.org/en-US/firefox/addon/status-4-evar/versions/?page=1#version-2015.08.19.02b
