### ISSUE TITLE
S4E partially broken in latest Nightly 44.0a1

### ISSUE THREAD

**Issue by Vangelis66** [SparkyBluefang/S4E#32]
Hi Bluefang - many thanks for this great addon, 
which I've been using faithfully since its early days...

My specs:
OS: WinVista SP2 x86 en-US
Firefox version: Nightly 44.0a1
build ID: Mozilla/5.0 (Windows NT 6.0; rv:44.0) Gecko/20100101 Firefox/44.0 ID:20151009030230 CSet: d01dd42e654b8735d86f9e7c723cc869a3b56798
S4E version: 2015.08.19.02b
CTR version: 1.4.1

Last good build: 20151007030205, cset=d1c5a7c5b433
First bad build: 20151008030232, cset=a955ea9382af
Regression range:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d1c5a7c5b433&tochange=a955ea9382af

Description:
After Nightly updated from 20151007030205 to 20151008030232: 
1. Status-bar panel vanished; 2 addons had their icons placed there 
(IPLogger & Version in Add-on bar).
I also have CTR installed, after going to "Customize" mode, 
I discovered the status-bar panel had migrated onto CTR's 
addon-bar; I put it back onto S4E's status-bar.
2. In S4E's settings, I have "Show progress in the Location Bar" 
checked, "Line style" set to "fill", "Use a custom style" checked, 
I've picked a solid blue colour (#3366FF). 
After the update, those settings aren't being honoured, 
instead "Line style" alternates between top/bottom randomly, 
and the colour is permanently set to a light blue (turquoise); 
any attempt to modify those settings is in vain...
I believe these posts:
http://forums.mozillazine.org/viewtopic.php?p=14360579#p14360579
http://forums.mozillazine.org/viewtopic.php?p=14360309#p14360309
describe the same issue...
3. In S4E's settings, I have "Progress->Toolbar->Use a custom style" 
checked and have configured a custom colour and a local picture 
(#3366FF url("file:///D:/~path~to~/image.png") no-repeat left center).
Again, those custom settings are not observed, instead I get a solid 
turquoise colour (like in 2) in the status-bar progress indicator...

I believe this breakage of S4E has to do with the issue 
discussed in this Mozillazine thread:
http://forums.mozillazine.org/viewtopic.php?f=23&t=2966543
So a code rewrite would have to be undertaken...
I don't understand the code inside S4E, 
all I can hope for is that you need only edit little code 
in order to restore S4E in its previous working state...

Many thanks for this awesome addon!
Vangelis.

**Comment by SparkyBluefang** [comment]
Should be fixed by 174d829

**Comment by Vangelis66** [comment]
Many thanks, Matt :-) !

 I've installed the latest .xpi from AMO, 
(2015.10.10.15b), at first glance it looks 
as though all is sorted out!
 But, of course, this is Nightly territory here, 
ain't no way of tellin' when Mozilla 
will screw things up again...
 
Much obliged for the quick fix...
