### ISSUE TITLE
Download Status icon is double height 

### ISSUE THREAD

**Issue by resuna** [SparkyBluefang/S4E#37]
I'm on an on iMac with one Retina and one non-Retina display, which may have something to do with it.
I'm also using Classic Theme restorer, so my workaround is to remove the download icons and SFE bar and move the status item to the CTR bar. Seems to work OK.

**Comment by resuna** [comment]
Only problem with the workaround is the download text box opens up at the lower left of the window, instead of under the download arrow. Is there a way to disable the override of the standard download behavior?

**Comment by m-schmitt** [comment]
Download Status icon is normal height on my two non-Retina Macs. Copied entire Firefox profile to a Retina Mac; on that Mac the Download Status icon is now extra-tall, increasing height of the entire status bar.
