### ISSUE TITLE
"XML Parsing Error: undefined entity" on new install with Developer Edition?

### ISSUE THREAD

**Issue by surashu** [SparkyBluefang/S4E#39]
I installed it on Firefox Developer Edition and got this error whenever I try to open the preferences. Any ideas?

![screenshot 21](https://cloud.githubusercontent.com/assets/12764163/16180552/03587d48-36bb-11e6-86b6-4364ef1b5185.png)

**Comment by jgjake2** [comment]
A quick fix is to replace "&aboutWarningButton.label;" with "Warning". Works on Nightly 50.0a1

**Comment by surashu** [comment]
@jgjake2 How exactly do I replace it? Where do I need to go to edit which?

**Comment by jgjake2** [comment]
@surashu Go to your extensions folder and either extract the "status4evar@caligonstudios.com.xpi" or use an archive manager (like 7z) to navigate (or just set the "extensions.alwaysUnpack" pref to true and reinstall the extension). Then just edit the "chrome/content/prefs.xul" as I said above. Then just restart firefox (be sure to clear your XUL cache) and tha'ts it.

**Comment by surashu** [comment]
@jgjake2 It gets disabled when I try to modify the `prefs.xul`.

![screenshot 23](https://cloud.githubusercontent.com/assets/12764163/16214372/34730e32-378a-11e6-90cd-01408ddb4f5e.png)

**Comment by jgjake2** [comment]
@surashu Set "xpinstall.signatures.required" to false.

**Comment by surashu** [comment]
@jgjake2 That did the trick, thanks! Should I leave this thread "Open" seeing as it's a workaround than an actual fix from the dev?
