### ISSUE TITLE
Preferences Broken

### ISSUE THREAD

**Issue by simion63** [SparkyBluefang/S4E#41]
Love your add-on - however your preferences Link is very **broken** at the moment - it is showing an XML Parse error 

XML Parsing Error: undefined entity
Location: chrome://status4evar/content/prefs.xul
Line Number 424, Column 8:

<button id="warningButton" command="stat

Can you please fix asap
Many thanks

**Comment by SparkyBluefang** [comment]
Duplicate of #39
