### ISSUE TITLE
Old Add-ons seem to be broken since FF 54 55

### ISSUE THREAD

**Issue by Slim08** [SparkyBluefang/S4E#48]
https://addons.mozilla.org/en-US/firefox/addon/live-ip-address/?src=search
https://addons.mozilla.org/en-US/firefox/addon/foxbox/?src=search

both used the statusbar to display and both seem to be broken since the last 3 or 4 updates of FF from 54 to 55

I'm using Nightly 55.0a1 (2017-03-09) (64-Bit)

**Comment by rmenessec** [comment]
@Slim08, I just had this problem, and I was able to fix it by installing the development version of S4E.

You didn't specify what kind of broken you meant, so I'll share: the S4E elements were still available, but the status text widget merely read "Status Text," and did not change for mouseover, navigation, or page draw events.

**Comment by AnthoniG** [comment]
How do I install it via the Development version please ?

**Comment by bormotov** [comment]
just released FF55 - broken
Not show url under cursor, for example.

**Comment by frank-github** [comment]
same here, after install of Firefox 55 Status-4-Evar is broken, no statusbar anymore

**Comment by frank-github** [comment]
beta-version of status-4-evar fixed problem
https://addons.mozilla.org/de/firefox/addon/status-4-evar/versions/2017.03.19.12b

**Comment by albertalbs** [comment]
@frank-github But that is old version.
