### ISSUE TITLE
Waterfox update breaks S4E

### ISSUE THREAD

**Issue by rebop** [SparkyBluefang/S4E#55]
Hi folks,
Waterfox updated yesterday to Classic 2019-10. Previously S4E worked flawlessly. Now, the only glitch I see is that the progress bar is green regardless how S4E is set. About:config and prefs.js both show the settings I have made perfectly. Its as if S4E no longer reads those settings.

Is there a fix?

Thanks so much.

**Comment by dodona2** [comment]
hovering over *any* link always displays "Status Text" at the left corner in the status bar.  Otherwise it works with my  Classic 2019-10. Any clue?

**Comment by rebop** [comment]
Hovering works for me. All that "seems" not to is the custom color of the progress bar. As mentioned, about:config looks proper:
![about](https://user-images.githubusercontent.com/13785042/67680552-b28c2000-f948-11e9-92b3-8ff8b5d0647d.JPG)

**Comment by hawkeye116477** [comment]
On console I saw error `this.watch is not a function"`, so maybe that's because `object.prototype.watch` was removed, because it caused problems with some websites like `mlb.com`.
Replacement for Object.prototype.watch exists (`https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy`).

**Comment by dodona2** [comment]
hovering works with linux/fedora 30. The above mentioned problem only occurs under windows 10.

**Comment by rebop** [comment]
i have no issues with hovering in Windows 10. But the progress bar issue in BOTH Windows 7 ad Windows 10.

**Comment by grahamperrin** [comment]
@JustOff ▲ and https://github.com/MrAlex94/Waterfox/issues/1238#issuecomment-547204716

**Comment by 613TheEvil** [comment]
It no longer works, sadly. Can a fix be found? I hate the hovering links!

**Comment by 9jkh** [comment]
S4E with 2019.10  now shows anemic, very thin progress bar. Please see OP at
https://www.reddit.com/r/waterfox/comments/docu2c/201910_status4evar_addon_progress_bar_much/

The update appears to have adversely affected other extensions besides this one. Awaiting a fix as soon as possible.

**Comment by rebop** [comment]
Does not look like the browsers are going to change, though I hope they reconsider. Any chance to get Staus 4 Evar updated to work around this?

**Comment by grahamperrin** [comment]
> Does not look like the browsers are going to change, 

https://github.com/MoonchildProductions/UXP/commit/ff881bdb6795e0f307b93919f98f454bedde4bb6

> Any chance to get Staus 4 Evar updated to work around this?

FYI maybe worth subscribing to https://github.com/JustOff/L4E/issues/1 although please note that (fork of Status-4-Evar) Location-4-Evar is for Pale Moon; not compatible with Waterfox Classic.

**Comment by SparkyBluefang** [comment]
S4E only officially supported Firefox, and I don't use any of the forks. So when Firefox dropped support for XUL extensions, S4E became unsupported.

You're welcome to create a fork and continue developing. Though I do request that you change the extension ID and namespace if you plan on publishing a new version.

i.e.
```sh
# Replace all "caligonstudios.com" with "developer.com"
find . -type f -not -path "./.git/*" -not -name ChangeLog -exec sed -i 's/caligonstudios.com/developer.com/g' '{}' \;

# Replace all "caligon" with "namespace"
find . -type f -not -path "./.git/*" -not -name ChangeLog -exec sed -i 's/caligon/namespace/g' '{}' \;
```

**Comment by rebop** [comment]
> 
> 
> S4E only officially supported Firefox, and I don't use any of the forks. So when Firefox dropped support for XUL extensions, S4E became unsupported.
> 
> You're welcome to create a fork and continue developing. Though I do request that you change the extension ID and namespace if you plan on publishing a new version.
>
If directed at me, I am not a programmer. And Waterfox "Classic" does support XUL. In my opinion its the reason for its being! So the WF removal of those classes broke S4E. So either WF needs to add them back and "seems" to be saying no as they were removed because they broke "some" websites, or S4E as it is pre removal of XUL needs a tweak. I'd love to see one or the other.

**Comment by hawkeye116477** [comment]
If author doesn't want to rewrite few things, then simpler fix could by done by just adding polyfill to extension (https://github.com/MoonchildProductions/UXP/commit/ff881bdb6795e0f307b93919f98f454bedde4bb6). 
PS: Maybe in the future release of Waterfox, status bar will be integrated, but it might be less advanced just like on Vivaldi.

**Comment by rebop** [comment]
I'd be happy to try that on Waterfox if you tell me what I need to do to add that. Remember, I am just a user. Perhaps a power user, but not a programmer.

**Comment by hawkeye116477** [comment]
Fixed version available on https://github.com/hawkeye116477/S4E/releases

**Comment by rebop** [comment]
Thank you!!!!

  _____

**Comment by rebop** [comment]
Working as expected with the exception that I can no longer customize the status bar. It overlaps another bar so elements cannot be rearranged or changed.
![image](https://user-images.githubusercontent.com/13785042/68546648-87b0bb80-038d-11ea-9335-0a73869273f5.png)

**Comment by rebop** [comment]
UPDATE:

With multiple tabs open, the customize has the two toolbars overlapping. With only one tab open, customize works as expected and two toolbars are visible and customizable.

**Comment by hawkeye116477** [comment]
@rebop I forgot to mention that you should disable old Status-4-Evar.

**Comment by rebop** [comment]
I removed it when I installed the new version :)

  _____

**Comment by rebop** [comment]
UPDATE: Takes more than just a few to occlude the status bar from customization by the tabs at the bottom. Two did not do it. A small session of 17 tabs did right away. Seems need to be enough to span the bottom of the browser window with tabs before the tabs occlude the status bar from customizing. Make sense?

**Comment by grahamperrin** [comment]
I see a minor issue but I'll not report it here. I might not report it at all `:-)`  

(It might be desktop environment theme-related, not at the extension level.) 

Big thanks!

**Comment by crudebuster** [comment]
Well, the fork works so I want to thank Sparky for all his work and support by these years.
Maybe someday we'll have a browser that gives back all the freedom Firefox insists to scrap while giving back horse manure.

**Comment by 9jkh** [comment]
Grateful for the work that went into this, but doesn't change the issue I'm still having, which is the very skinny, as in thin, progress bar. Everything else was working in the original version, so still using that.

**Comment by crudebuster** [comment]
> 
> 
> Grateful for the work that went into this, but doesn't change the issue I'm still having, which is the very skinny, as in thin, progress bar. Everything else was working in the original version, so still using that.

Get the fork https://github.com/hawkeye116477/S4E/releases , it's fixed.
